### PR TITLE
add: tokens to reflect correctly Chainport's TVL

### PR DESCRIPTION
**Pull request by odedNea**
Hi L2Beat,
Thank you for adding Chainport to the platform!
To reflect Chainport's TVL correctly, we've added a few tokens.

### CODE REVIEW

**Comment by odedNea** [comment]
@lucadonnoh  any update with this please?

**Comment by antooni** [comment]
There is no need to add "formula" field to every config, please only add new tokens, do not modify the current ones

**Review by antooni — CHANGES_REQUESTED** [review]
Please do not modify existing token entries

**Comment by odedNea** [comment]
@antooni I've fixed the PR according to your comments.

**Comment by odedNea** [comment]
Hi @antooni 
Please let me know if there's anything to edit in the PR, or if it can be merged.
Thank you

**Comment by odedNea** [comment]
@antooni any updates?

**Review by maciekzygmunt — CHANGES_REQUESTED** [review]
Change category of every added token from `ether` to `other`

**Comment by antooni** [comment]
@odedNea can you resolve the requested changes?

**Comment by odedNea** [comment]
@antooni @maciekzygmunt 
Resolved

**Review by antooni — APPROVED** [review]

**Review by maciekzygmunt — APPROVED** [review]

**Pull request merged**
