### PR TITLE
Adding BlockSpot

### PR DESCRIPTION
**Pull request by AthDevETH**
Adding Layer 2 Network BlockSpot

### CODE REVIEW

**Comment by luke7211** [comment]
@degenstealthdev what happened here ? 
image

**Comment by degenstealthdev** [comment]
> @degenstealthdev what happened here ? image

Not Sure but we updated our X on the PR https://twitter.com/BlockSpotL22

Thank you

**Comment by mateuszradomski** [comment]
The CI checks are failing, please fix them.

**Review by mateuszradomski — CHANGES_REQUESTED** [review]
The CI checks are failing, please fix them

**Comment by lucadonnoh** [comment]
is it live? https://x.com/BlockSpotL22/status/1727363372449198336?s=20

**Comment by lucadonnoh** [comment]
the chain seems to be live

**Pull request closed without merging**
