### PR TITLE
Add swell pre-launch discovery

### PR DESCRIPTION
**Pull request by sekuba**
do we need the discovery in .ts (and move to inreview) to have update-monitor catch it?

### CODE REVIEW

**Comment by lucadonnoh** [comment]
> do we need the discovery in .ts (and move to inreview) to have update-monitor catch it?

no, it works for eigen without a ts :p

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
i don't see anything that would tell us here that they launched. Maybe we need to monitor `rescueERC20` calls?

**Comment by sekuba** [comment]
i think eigen might only work because of `packages/config/src/onChainProjects.ts` 
> anything that would tell us here that they launched

oh yeah true, but at least we would def get the multisig nonce since they have to push a timelock tx to do anything with the escrow funds (like bridging) idk if that would be enough

**Comment by lucadonnoh** [comment]
> oh yeah true, but at least we would def get the multisig nonce since they have to push a timelock tx to do anything with the escrow funds (like bridging) idk if that would be enough

then add this in meta.json so we don't forget

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
