### PR TITLE
added palm and capx

### PR DESCRIPTION
**Pull request by sahilkamra2**
Added Palm network and Capx

### CODE REVIEW

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
icons must be 256x256 PNGs under 10KB

**Comment by sahilkamra2** [comment]
resized icons

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
not 256x256, please fix

**Comment by sahilkamra2** [comment]
@lucadonnoh resized to 256*256 and under 10kb

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
palm doesn't look like a zk rollup but a separate L1, am i missing something?

**Comment by sahilkamra2** [comment]
It is an L2, You can read the docs here --> https://docs.palm.io/introduction

**Comment by lucadonnoh** [comment]
i see no mentions of zk proofs, can you point me the specific page in the docs?

**Comment by sahilkamra2** [comment]
https://cointelegraph.com/news/nft-palm-network-to-become-polygon-zk-supernet

**Comment by lucadonnoh** [comment]
i see, thanks for the context!!

**Comment by lucadonnoh** [comment]
Resolves L2B-2226

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
