### PR TITLE
Add MXCzkEVM config

### PR DESCRIPTION
**Pull request by luanxu-mxc**
Added MXCzkEVM network, and because MXCzkEVM runs on Arbitrum One, it is unable to provide escrows and discovery.

### CODE REVIEW

**Comment by lucadonnoh** [comment]
the project is an L3 right? we currently don't support them but i will discuss this internally, thanks for the PR!

**Comment by luanxu-mxc** [comment]
> the project is an L3 right? we currently don't support them but i will discuss this internally, thanks for the PR!

Thanks, you guys can also list us as L2 temporarily if you want, as we have already launched mainnet.

**Comment by antooni** [comment]
We currently do not support L3s

**Comment by sheenhx** [comment]
can you just list MXC as a Layer 2 temporarily ?

**Comment by lucadonnoh** [comment]
no since it's not an L2, we're working on adding L3 as well

**Comment by sheenhx** [comment]
@lucadonnoh can you add us as Layer2? Our chain is quite active now

**Comment by sheenhx** [comment]
Hey I saw your website now supports layer 3 can you reopen this issue

**Pull request closed without merging**
