### PR TITLE
Add events config

### PR DESCRIPTION
**Pull request by antooni**
BEFORE: There is an already merged EventUpdater but configs of projects are empty

AFTER: Project have filled config and EventUpdater is ready to sync behind feature flag

Resolves L2B-28

### CODE REVIEW

**Comment by antooni** [comment]
Resolves L2B-28

**Review by krzkaczor — CHANGES_REQUESTED** [review]
Once merged, it will kick off backedn sync of events. I wouldn't merge it as we are redoing the whole thing.

**Comment by sz-piotr** [comment]
> Once merged, it will kick off backend sync of events. I wouldn't merge it as we are redoing the whole thing.

Maybe if we just add a flag to prevent syncing it would be fine to have the configuration on master

**Comment by krzkaczor** [comment]
actually good idea, @antooni can you add here some flag that would prevent the whole thing from running? Then we can merge this PR.

**Review by krzkaczor — APPROVED** [review]

**Pull request merged**
