### PR TITLE
Adding Bugless DApp into L3 section

### PR DESCRIPTION
**Pull request by claudioantonio**
BugLess is a trustless bug bounty platform powered by Cartesi Rollups, designed to address the issues faced by traditional bug bounty programs.

### CODE REVIEW

**Comment by mateuszradomski** [comment]
Hi,

Please refer to the [CONTRIBUTING.md](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#add-your-layer-3-project-to-the-website) to make sure that all CI checks are passing. You'll find that described in step 6.

**Comment by claudioantonio** [comment]
> Hi,
> 
> Please refer to the [CONTRIBUTING.md](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#add-your-layer-3-project-to-the-website) to make sure that all CI checks are passing. You'll find that described in step 6.

Sorry for that @mateuszradomski , I just run format:fix.
I will run the other checkers. 🙏

**Comment by claudioantonio** [comment]
@mateuszradomski I will check the tests that are broken.

**Comment by claudioantonio** [comment]
> @mateuszradomski I will check the tests that are broken.

All checks are beautiful now, @mateuszradomski !

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
