### PR TITLE
Add Proof of Play Apex (full)

### PR DESCRIPTION
**Pull request by sekuba**
Resolves L2B-4698

Apex is an orbit stack L3 with AnyTrust DA settling on Arbitrum. They deployed with ArbOS 10 and are using the default escrows with ETH only.
Deploy tx: [0x2b3afe91774ac66b00b40909ee92830313aea5687731aa8ba10f0dfc47af7046](https://dashboard.tenderly.co/tx/arbitrum/0x2b3afe91774ac66b00b40909ee92830313aea5687731aa8ba10f0dfc47af7046)

### CODE REVIEW

**Comment by sekuba** [comment]
hello github y no merge

**Comment by lucadonnoh** [comment]
btw we're missing info related to the DAC

**Comment by sekuba** [comment]
oh i see ok

**Comment by lucadonnoh** [comment]
but i see it's the same for all the projects, we should remember that tho

**Comment by lucadonnoh** [comment]
we should add the DAC in the permission section but i think it's not trivial

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
