### PR TITLE
Move OP stack to discovery driven data (batch 2)

### PR DESCRIPTION
**Pull request by sekuba**
Part of L2B-7544

all op stacks discoverydriven starting from blast tvl downwards

### CODE REVIEW

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
image

i know this was present already, but why does it happen? (blast)

**Comment by lucadonnoh** [comment]
rest lgtm

**Comment by sekuba** [comment]
Dai vault had empty token brackets since Blast was added :p

**Comment by lucadonnoh** [comment]
> Dai vault had empty token brackets since Blast was added :p

isn’t this because we’re tracking USDB already and we shouldn’t double count?

**Comment by sekuba** [comment]
yeeees of course! what should we do?
1) yeet whole escrow (it is still described in the contracts section as usdyieldprovider)
2) idk 1 is very good choice prly

**Comment by lucadonnoh** [comment]
i don’t know. please revert the change and discuss this tomorrow during standup (i won’t be there cuz traveling) and i’ll approva this PR in the meantime

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
