### PR TITLE
Add mTokens to Manta Pacific

### PR DESCRIPTION
**Pull request by DanielZhangReal**
- [mBTC](https://pacific-explorer.manta.network/token/0x1468177DbCb2a772F3d182d2F1358d442B553089)
- [mETH](https://pacific-explorer.manta.network/token/0xACCBC418a994a27a75644d8d591afC22FaBA594e)
- [mUSD](https://pacific-explorer.manta.network/token/0x649d4524897cE85A864DC2a2D5A11Adb3044f44a)

[Manta CeDeFi protocol on DeBank](https://debank.com/protocols/manta_cedefi)
[Manta CeDeFi](https://cedefi.manta.network/)

### CODE REVIEW

**Comment by sekuba** [comment]
These tokens are [ProxyAdmin](https://pacific-explorer.manta.network/address/0x0172881051518db699cbbf5b8493d20a375819ae)-->[EOA](https://pacific-explorer.manta.network/address/0x3fc3aed5efc4fd6ca4785a436e7d5ed749d05fe0) owned. 
So the EOA has full admin / minting rights.

- They are LayerZero-bridged
- They accrue staking rewards and will diverge from the value of their base assets
- they are not listed on coingecko

This combination makes it difficult for us to list them as their base assets because they differ quite a lot from them...

**Comment by DanielZhangReal** [comment]
hello @sekuba, thanks for the reply.

https://mantanetwork.medium.com/manta-cedefi-boosting-yield-and-security-4728b723be69

This is Docs related to CeDeFi mToken, which explains the technical details and interaction process of CeDeFi products. mToken is the mapping of the original token.

Our product is similar to Ethena (USDe), both use Ceffu to custody the original assets and mint the corresponding mToken on the chain.

So we first need to list mToken on CoinGecko right?

**Comment by sekuba** [comment]
Yes, if the mTokens accrue the APY by a changing ratio to the underlying, we need coingecko price data.

**Comment by DanielZhangReal** [comment]
> Yes, if the mTokens accrue the APY by a changing ratio to the underlying, we need coingecko price data.

https://www.coingecko.com/en/coins/manta-mbtc
https://www.coingecko.com/en/coins/manta-meth
https://www.coingecko.com/en/coins/manta-musd

hello @sekuba, mToken has been submitted on CoinGecko and has price data. Please help follow up on this PR

**Comment by sekuba** [comment]
gm, thanks for the ping :) continued in #4178

**Pull request closed without merging**
