### PR TITLE
Add bridges to Starknet

### PR DESCRIPTION
**Pull request by lucadonnoh**
Adds wstETH and rETH bridges.

Resolves L2B-1953

### CODE REVIEW

**Review by antooni — CHANGES_REQUESTED** [review]
Does starknet keep list of bridges onchain? It would be ideal if those addresses were discovered and not hardcoded into initial ones. How can we be sure that it is indeed a bridge to starknet?

**Comment by lucadonnoh** [comment]
i'll take another look, but i'm not sure that they can be discovered

**Comment by lucadonnoh** [comment]
i don't see anything onchain, just asked them in the tg group with starkware if they have such a registry

**Comment by antooni** [comment]
It depends, let's wait for today, I am just worried we will forget about it, but if you feel like you will not forget then merge it

**Review by antooni — APPROVED** [review]

**Pull request merged**
