### PR TITLE
Add DA references

### PR DESCRIPTION
**Pull request by vincfurc**
resolves L2B-7605

### CODE REVIEW

**Comment by lucadonnoh** [comment]
this is not what i meant, i imagined references: [] as we have in scaling projects, at the end if each section

**Comment by radinat** [comment]
> this is not what i meant, i imagined references: [] as we have in scaling projects, at the end if each section

But is it an issue if it's like this? I think this way it's even easier to know what the references are about?

**Comment by lucadonnoh** [comment]
@radinat are you suggesting we should update all scaling pages?

**Comment by radinat** [comment]
> @radinat are you suggesting we should update all scaling pages?

@lucadonnoh not necessarily, in the markdown sections on the scaling pages we're already adding references in the same way (State derivation, State validation)

**Comment by lucadonnoh** [comment]
i think we should be consistent

**Pull request merged**
