### PR TITLE
Add cli flag --mermaid

### PR DESCRIPTION
**Pull request by michalsidzej**
Resolves L2B-1696

### CODE REVIEW

**Comment by antooni** [comment]
When running mermaid at the end of the output show the link to mermaid.live, maybe also copy markup to clipboard?

**Comment by michalsidzej** [comment]
> When running mermaid at the end of the output show the link to mermaid.live, maybe also copy markup to clipboard?
> 
> [sindresorhus/clipboardy](https://github.com/sindresorhus/clipboardy)

I hope you like the newest commit 😃

**Comment by lucadonnoh** [comment]
what about adding `yarn invert [project]`?

**Comment by michalsidzej** [comment]
> 

That's how it works rn :)

**Comment by antooni** [comment]
> > 
> 
> That's how it works rn :)

Love it!

**Pull request merged**
