### PR TITLE
add dapp token

### PR DESCRIPTION
**Pull request by colinlyguo**
pencils protocol is a project built in scroll and initializes the token contract in Ethereum.
for more info, can see their website: https://pencilsprotocol.io/

### CODE REVIEW

**Comment by colinlyguo** [comment]
@sekuba pls take a look.

**Review by Danni1326 — APPROVED** [review]

**Comment by sekuba** [comment]
hey, we need coingecko circulating supply for this since it [seems to be vesting / locked on scroll](https://scrollscan.com/address/0xc533593fc55f67198a191731ac0b707b2aa19c40), so we would overcount by counting the canonical bridge TVL

**Comment by colinlyguo** [comment]
> hey, we need coingecko circulating supply for this since it [seems to be vesting / locked on scroll](https://scrollscan.com/address/0xc533593fc55f67198a191731ac0b707b2aa19c40), so we would overcount by counting the canonical bridge TVL

got it. btw, does the Market cap field in https://coinmarketcap.com/currencies/penpad/ represent the circulating supply?

**Comment by sekuba** [comment]
image
yeah i think so

**Comment by colinlyguo** [comment]
> image yeah i think so

then we can use it? or we cannot use it since it's not verified (self-reported)?

**Comment by sekuba** [comment]
no we need coingecko since we are using their api, not coinmarketcap :/

**Review by Danni1326 — APPROVED** [review]

**Pull request closed without merging**
