### PR TITLE
Add BOB network

### PR DESCRIPTION
**Pull request by nud3l**
- Adds the BOB network (an OP Stack rollup)

### CODE REVIEW

**Comment by lucadonnoh** [comment]
we currently only supports network using Ethereum consensus (so Ethereum rollups or Ethereum validiums). My understanding from the docs is that the project didn't decide yet what to use (ETH vs BTC vs Celestia), right?

**Comment by nud3l** [comment]
We are using Ethereum consensus with an unmodified OP Stack. We may use Celestia or Bitcoin for DA but settlement will happen on Ethereum.

**Comment by lucadonnoh** [comment]
please fix tests

**Comment by danielsimao** [comment]
> please fix tests

Hey @lucadonnoh. I have added what was missing in the PR. I ran the linter and it is fine but the tests fail.

image

This does not seem to be related to our PR. Let me know if there is something else that we need do. Cheers

**Review by lucadonnoh — APPROVED** [review]

**Pull request merged**
