### PR TITLE
added RWA token to re.al tokens

### PR DESCRIPTION
**Pull request by chasebrownn**
Added RWA token to tokens for real chain.

### CODE REVIEW

**Comment by sekuba** [comment]
Sorry, we are currently unable to support this token:
- it has full 200G supply on all supported chains (would be doublecounted if added)
- the circulating supply on coingecko is spread over different L2s and ethereum

For the next time, please try to follow [this lil guide](https://github.com/l2beat/l2beat/blob/main/docs/tvl.md#token-guide)

thanks ;)

**Comment by chasebrownn** [comment]
RWA is not a cross chain token. It only exists on re.al so I’m confused as to your comment @sekuba

**Comment by sekuba** [comment]
Sorry for that, i was thinking about the Xend RWA with the same ticker.
Do you have a working rpc for me that is not real.drpc.org?

**Comment by chasebrownn** [comment]
@sekuba No public rpcs, but we have private rpcs that we can provide you guys as long as it's obfuscated. Can we reopen this PR?

**Comment by sekuba** [comment]
so the drpc worked just now in contrast to this morning and i was able to add it
will see how it goes and msg you again in case we need a better one 
(if they work i prefer the public ones so we do not have to manage the secrets)
i continued at #4505 ;)

**Pull request closed without merging**
