### PR TITLE
Add various tokens to MODE

### PR DESCRIPTION
**Pull request by dananderson3999**
Added LZ-based tokens to Mode Network:
KelpDAO rsETH, KelpDAO Wrapped rsETH, Dinero pxETH, Ethena sUSDe, Ethena USDe, Ethena ENA

### CODE REVIEW

**Review by dananderson3999 — COMMENTED** [review]
also added Merlin BTC m-BTC.

**Review by mateuszradomski — CHANGES_REQUESTED** [review]
Hi,

Thank you for your contribution. After adding the tokens to the `tokens.jsonc` you also need to run `yarn tokens` in the `packages/config` directory. Also make sure that your PR passes all the CI checks, this is described in [point 6](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#add-your-layer-2-project-to-the-website).

**Comment by sekuba** [comment]
closing as the others except rsETH are low TVL right now

**Comment by sekuba** [comment]
yes for mbtc see #3450

**Pull request closed without merging**
