### PR TITLE
ZKFair mainnet launch

### PR DESCRIPTION
**Pull request by MortyYi**
ZKFair mainnet launch:
ZKFair is the first community ZK-L2 based on Polygon CDK and Celestia DA, championing fairness.
websites: https://zkfair.io/
socialMedia: https://docs.zkfair.io/
documentation: https://twitter.com/ZK_fair/

### CODE REVIEW

**Comment by MortyYi** [comment]
hello, @lucadonnoh. Our ZKFair mainnet is up, and about the pr, I have some question.
1. Do I need to generate the discovery/zkfair/ethereum/config.jsonc file? Or Would you mind help me out with that? Since It's seem like a little bit hard to do it.
2. Is it ok to only add the escrows related smart contract information for now? And we add the rest of it in next.
thanks very much :)

**Comment by lucadonnoh** [comment]
yes i'll take a look!

**Comment by MortyYi** [comment]
> yes i'll take a look!

Hi! Is there anything I have to do, or some information I need to provide?

**Comment by lucadonnoh** [comment]
moved here since i cannot push https://github.com/l2beat/l2beat/pull/2423

**Pull request closed without merging**
