### PR TITLE
Add rest of missing tokens for Arbitrum

### PR DESCRIPTION
**Pull request by joshuacolvin0**

### CODE REVIEW

**Comment by sz-piotr** [comment]
Hey @joshuacolvin0. The PR is absolutely fine, but we need to rethink our policy of coins that we track. For example with PREMIA. It has only 1500 holders and is most actively traded on Sushiswap which we don't check for price currently. https://etherscan.io/token/0x6399c842dd2be3de30bf99bc7d1bbf6fa3650e70#tokenTrade. Not to mention the fact that it accounts for $0.07 of TVL. I'll get back to you once I get a clearer picture of what coins are acceptable :)

**Comment by joshuacolvin0** [comment]
Sounds good!

**Comment by sz-piotr** [comment]
As of #232 there are now (hopefully) clear guidelines as to what tokens can be added. You can read them here:
https://github.com/l2beat/l2beat/blob/a04122f62c2067d680e1f5ef6570186cbae34d22/packages/config/src/tokens.ts#L1-L26

To save you the trouble of checking the coins in this PR I went through them and checked myself:
- ALCH - Rank 2425 - doesn't qualify
- BADGER - Rank 264 - OK
- CAP - Rank 1033 - doesn't qualify
- CELR - Rank 203 - OK
- CREAM - Rank 378 - doesn't qualify
- CRV - Rank 108 - OK
- EUX - Unlisted - doesn't qualify
- USX - Rank N/A - doesn't qualify
- DHT - Rank 864 - doesn't qualify
- DXD - Rank 703 - doesn't qualify
- FUSE - Rank 995 - doesn't qualify
- GMX - Rank N/A - doesn't qualify
- GRT - Rank 39 - OK
- MATH - Rank 259 - OK (this one has the least uniswap activity, but it should be fine)
- PL2 - Unlisted - doesn't qualify
- PREMIA - Rank 1244 - doesn't qualify
- RGT - Rank 340 - doesn't qualify
- SDT - Rank 786 - doesn't qualify
- SWPR - Unlisted - doesn't qualify
- sUSD - Rank 237 - OK
- VISR - Rank 721 - doesn't qualify
- WOO - Rank 218 - OK

**Comment by joshuacolvin0** [comment]
Updated, thanks!

**Pull request merged**
