### PR TITLE
Adding new token to re.al tokens

### PR DESCRIPTION
**Pull request by chasebrownn**
Adding USDR to real tokens list

`yarn tokens` was not working for me so if I can get an admin to perform that action that would be very helpful.

Thanks

### CODE REVIEW

**Comment by sekuba** [comment]
this stablecoin is depegged and they are planning a migration to a different CA

**Comment by sekuba** [comment]
yes, like for every coin we need valid coingecko price data though.. the only CG page i found was for the old coin

**Comment by chasebrownn** [comment]
@sekuba Its the same token.. just bridged. It’s not a different contract address.

**Comment by sekuba** [comment]
so the [price of 40 cents ](https://www.coingecko.com/en/coins/real-usd)is correct?
we would be very hesitant to add a token with a price feed from a different chain while the price is unpegged.

**Comment by chasebrownn** [comment]
Yes the price is correct. And what “migration” are you referring to?

**Comment by chasebrownn** [comment]
@sekuba Is there anything additionally I can provide for you?

**Comment by chasebrownn** [comment]
@sekuba Just nudging here

**Comment by sekuba** [comment]
sir, we are not adding the token in this state. 
* formally, we do not add any tokens with nonexisting price data for the chain they are added to. (this is why you could not succeed with the tokens script)
* informally, the info around this asset is chaotic at best and actually misleading from my short research (why is it - one year later - still not fully redeemed if that was what the team communicated as their goal... why are there farming campaigns for an asset that is illiquid, unpegged, and supposed to be sunset)

If you really are confident it is an essential asset in you eco, please put in some effort and help us understand what use-case there is for this token and what is the actual goal of the 'redemptions'/'migration' and we can make an exception for the formal problem mentioned above

**Comment by chasebrownn** [comment]
@sekuba We understand. Once redemption is completed the remaining USDR is going to be burned and deprecated anyway so it's not worth the hassle. Thanks for your help nonetheless.

**Comment by Danni1326** [comment]
I am completely new to cryptocurrency and and wasn't aware of the many
layers too it. On top of I am completely technologically declined. I
started a coinbase account, than a wallet, than I started to see NFT's and
Dapps.....needless to say I am trying to break generational poverty and to
try something completely knew, with a lack of computer skills and noone to
really learn from

**Comment by Danni1326** [comment]
Apologies for the misspelled words. I obtain a new phone am struggling a
bit to get everything half operable again. I do appreciate any guidance or
knowledge so this doesn't happen again I found a couple more address on the
block chains that look to be getting steady income on my behalf. I need to
relinquish the wallet apparently?!

**Pull request closed without merging**
