### PR TITLE
Updating Wormhole and Allbridge

### PR DESCRIPTION
**Pull request by hydrogenbond007**
- Changed Archival status
- Added resources
- Corrected Portal.ts 

The wormhole description were a bit off and needed some updating since

### CODE REVIEW

**Comment by hydrogenbond007** [comment]
Previous pull request #1857

**Comment by hydrogenbond007** [comment]
@luke7211 tagging in for review

**Comment by hydrogenbond007** [comment]
@luke7211 Bumping this up for review

**Comment by hydrogenbond007** [comment]
Yo, what happened @lucadonnoh ? I been waiting for review all along
image

**Comment by lucadonnoh** [comment]
we already have Portal here https://l2beat.com/bridges/projects/portal, and also i’m not sure why you decided to delete wormhole v1 from the archived tab

regarding the Third Party designation, that’s what a Permissioned network is so it was already correct

**Comment by hydrogenbond007** [comment]
Answering some of the questions 
- Portal is different because portal is a token bridge built on top of wormhole, not wormhole itself
- I did not know wormholev1 was archived, but most of the details were outdated so tried to update them
- as for "third party", it was not very clear. The permissioned network was clearer

Seems like I made some mistakes, will restructure the PR again.

**Pull request closed without merging**
