### PR TITLE
add token DAPP to scroll

### PR DESCRIPTION
**Pull request by georgehao**

### CODE REVIEW

**Comment by sekuba** [comment]
Hi, thanks for the PR,

To list DAPP on L2BEAT we need two more things:
* circulating supply on coingecko
* token contract verification on scrollscan

**Comment by georgehao** [comment]
Oh, sorry, I copy the wrong token address. Dapp is minted on L1 and bridge to Scroll chain. the address on scroll is : [0xb0643f7b3e2e2f10fe4e38728a763ec05f4adec3](https://scrollscan.com/token/0xb0643f7b3e2e2f10fe4e38728a763ec05f4adec3)

**Comment by georgehao** [comment]
Shall we reopen this pr?

**Comment by sekuba** [comment]
do you have the L1 address too?

**Comment by georgehao** [comment]
This is the l1 address: https://etherscan.io/token/0x5FC429110A64bC51b57Ca86dCE1714FD0fBec303

**Comment by sekuba** [comment]
thanks :) i'm afraid we still cannnot list it because circulating supply is not tracked on coingecko and we would inflate the TVL by ~20Mio without having the circulating value :/

**Pull request closed without merging**
