### PR TITLE
Add Stealthchain (upcoming)

### PR DESCRIPTION
**Pull request by lucadonnoh**
Resolves L2B-2328

### CODE REVIEW

**Comment by lucadonnoh** [comment]
@degenstealthdev can you provide a 256x256 logo?

**Comment by degenstealthdev** [comment]
@lucadonnoh 

Heres Logo 256x256

https://i.ibb.co/LNqhPBL/chain.png

Thank you

**Comment by lucadonnoh** [comment]
can you provide just the image without the text? otherwise it would be unreadable

**Comment by degenstealthdev** [comment]
Hello

Will this work? 

https://i.ibb.co/gtkczcY/256.png

Thank you

**Review by luke7211 — APPROVED** [review]

**Pull request merged**
