### PR TITLE
Adding upcoming honeypot DApp

### PR DESCRIPTION
**Pull request by claudioantonio**
Honeypot is a DApp designed to challenge the security of Cartesi Rollups. Bug hunters are incentivized to hack the application to obtain the funds locked in the rollup contract. Honeypot holds real assets with a dual objective: setting a financial benchmark for secure asset management and providing a gamified battlefield for the community to help audit and test Cartesi Rollups.
More info [here](https://medium.com/cartesi/cartesi-ecosystem-update-2023-124b384401cc#:~:text=Honeypot%20DApp%20on%20Mainnet)

### CODE REVIEW

**Comment by antooni** [comment]
Hey @claudioantonio,
what is the state of this PR? I see some TODOs, can I help you somehow?

**Comment by claudioantonio** [comment]
> Hey @claudioantonio, what is the state of this PR? I see some TODOs, can I help you somehow?

Hi @antooni ! These TODOs are related to info that will only have when the DApp is deployed on mainnet. For example, the smart contract address, the github repo link, etc.

The idea would be to update the `honeypot.ts` file right after the Mainnet deployment.

Can I keep it? Or do you prefer that I remove these comments?

**Comment by claudioantonio** [comment]
@antooni 

> TBH @claudioantonio I am not sure about this one, you filled purpose with "bug bounty", can you provide some reasoning behind this? 

Sure @antooni ! You can think of the Honeypot DApp as a kind of game/challenge for developers. 😄 There will be some amount of DAI (that will increase over time) locked in the DApp and the developers have to find a way to transfer these DAIs from the DApp (break the pot). It is a challenge for developers and a security test for Cartesi's Rollups solution.

Do you have a suggestion for a better purpose that we should use?

> why should we list it on L2BEAT?

The Honeypot is a DApp developed using a Layer-2 solution (more specifically an application-specific rollups) which has its security derived from L1 and has some value locked in it.

> what technologies are there, 

As mentioned above the honeypot was built using the Cartesi Rollups SDK which is an application-specific rollups with a Linux runtime and Ethereum's security guarantees. You can check the Cartesi Rollups [thesis here](https://medium.com/cartesi/application-specific-rollups-e12ed5d9de01).

At the heart of the Cartesi Rollups solution there is the Cartesi Machine which is a real Linux runtime environment. It allows developers to use the programming languages and tools of their choice to write the code for the logic of their DApp's. You can read more about the Cartesi Machine [here](https://docs.cartesi.io/cartesi-machine/).

Cartesi Rollups official examples written in Python, JavaScript/Typescript, Rust and C++ can be found [here](https://github.com/cartesi/rollups-examples#examples).

> what are the smart contracts, what is the desired architecture?

I will create a diagram to show the solution design. Just for my planning, is it a requirement for the DApp to appear as an upcoming project?

Please let me know any other question that you have, ok?

**Comment by claudioantonio** [comment]
Hi @antooni !
As promised here comes a diagram that shows the overall solution design for the Honeypot DApp and its underlying technology (Cartesi Application-specific Rollups).

Some observations:
- Inside the Ethereum network, the orange boxes are the Cartesi Rollups contracts that are common to all DApps built using Cartesi Rollups and the black box is the specific instance for the Honeypot DApp.
- You can see the DApp owner/deployer creating the Honeypot DApp instance and depositing the DAIs to the pot.
- Cartesi will initially provide a execution infrastructure where the validator node for the Honeypot DApp will run. This validator node is a specific instance for the Honeypot DApp with it own Cartesi Machine (Linux runtime where the Honeypot logic will run). The validator is responsible to save the rollups state for the DApp at the end of each epoch and also to make claim in case of disputes.

L2Beat - Honeypot solution design with Cartesi Rollups

Please take a look and don't hesitate to make any question you need, ok?

**Comment by luke7211** [comment]
Hey Claudio, pls have a look at my discord dm, I would like to have a chat
about HoneyPot

**Comment by claudioantonio** [comment]
> Hey Claudio, pls have a look at my discord dm, I would like to have a chat about HoneyPot 

Thanks @luke7211 ! Already answered there.

**Comment by claudioantonio** [comment]
Commit [ab5f02](https://github.com/l2beat/l2beat/pull/1391/commits/ab5f027389e7db9166475ac756f6f57715978ede) adds Cartesi provider icon in the technology column of the project's table. See screenshot below.
image

**Pull request closed without merging**
