### PR TITLE
Add Upgrades & Governance section for Starknet

### PR DESCRIPTION
**Pull request by mzoettl**
starknet-upgrade-governance

### CODE REVIEW

**Comment by sekuba** [comment]
hey @mzoettl do you have the .excalidraw source of your diagram? i'd like to add it and do some slight modifications

**Comment by mzoettl** [comment]
> hey @mzoettl do you have the .excalidraw source of your diagram? i'd like to add it and make some slight modifications

@sekuba Hi, sure thing! Apparently GitHub doesn't support .excalidraw files to be uploaded. Are you able to copy the content from this link? https://excalidraw.com/#json=YRprNT5dSVeMAZ8D44FtL,R0yVYTv6L67gll3KX79ttQ

**Comment by sekuba** [comment]
No, but i think you can share a link to the excalidraw page or you could send it on telegram (t.me/sekuba) ;)

**Comment by sekuba** [comment]
closing this, it is continued in #3170 ;)

**Pull request closed without merging**
