### PR TITLE
Remove incomplete banner

### PR DESCRIPTION
**Pull request by lucadonnoh**
deleted `isIncomplete`, but what do i need to do to delete this banner too? (solved by #1644)
image
cc @antooni

### CODE REVIEW

**Comment by antooni** [comment]
@lucadonnoh I think this is the copy that we have on every bridge page, please contact @luke7211 whether we want to remove it or make it conditional on some pages

**Comment by lucadonnoh** [comment]
i quickly skimmed through the code and it looked conditional, could you please check that this is not the case?

**Comment by michalsidzej** [comment]
> i quickly skimmed through the code and it looked conditional, could you please check that this is not the case?

This is coming from here: https://github.com/l2beat/l2beat/blob/f7692f6a271c095f4d4c950e072ce0e335be33e2/packages/frontend/src/pages/bridges-projects/props/getTechnologyOverview.ts#L39. 

There's a bug (fixed by https://github.com/l2beat/l2beat/pull/1644). After merging this PR, it should work as expected.

**Review by michalsidzej — APPROVED** [review]
The bug was fixed, LGTM

**Pull request merged**
