### PR TITLE
Remove L2BEAT

### PR DESCRIPTION
**Pull request by mateuszradomski**
Small refactoring 🥰

### CODE REVIEW

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
there are some files left smh my head
image

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
there are some files left smh my head
image

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
there are some files left smh my head
image

**Review by lucadonnoh — CHANGES_REQUESTED** [review]
there are some files left smh my head
image

**Comment by mateuszradomski** [comment]
Closing because CI keeps failing and I don't know how to fix it. 😡

**Pull request closed without merging**
