### PR TITLE
Added and updates some explorer links

### PR DESCRIPTION
**Pull request by iJaack**
- Blast, Mode and OP Superscan explorers added
- Taiko explorer updated (the existing link points to the deprecated testnet)

### CODE REVIEW

**Comment by mateuszradomski** [comment]
Hi, please refer to the [point number 6](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#add-your-layer-2-project-to-the-website) to fix issues with CI failing.

**Comment by iJaack** [comment]
I double checked, but I don't see any formatting error. Should I put the `/` ahead of all links?

Otherwise I don't see any error, I just replaced URLs.

**Comment by iJaack** [comment]
Everything's running smooth locally, I don't understand why it doesn't work in production..

**Review by mateuszradomski — APPROVED** [review]
Thank you for your contribution!

Fixed the formatting myself.

Next time please read the [CONTRIBUTING.md](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md) from start to finish.
Formatting errors are fixed with `yarn format:fix`.

**Pull request merged**
